/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BaseProjectOptions {
  /**
   * The name of the project
   */
  name: string;
  /**
   * Mark the project as private
   */
  private?: boolean;
  /**
   * A description of the project
   */
  description?: string;
  /**
   * The repository for the project
   */
  repository?: string;
  [k: string]: unknown;
}
