/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NewTsLibProjectOptions {
  /**
   * The directory name to create the development environment in.
   */
  directory?: string;
  /**
   * The name of the project
   */
  name: string;
  /**
   * Adds web bundler
   */
  web?: boolean;
  /**
   * Mark the project as private
   */
  private?: boolean;
  /**
   * A description of the project
   */
  description?: string;
  /**
   * The repository for the project
   */
  repository?: string;
  /**
   * Author
   */
  author?: string;
  /**
   * License
   */
  license?: string;
  /**
   * Do not initialize a git repository.
   */
  skipGit?: boolean;
  /**
   * Initial git repository commit information.
   */
  commit?:
    | boolean
    | {
        name: string;
        email: string;
        message?: string;
        [k: string]: unknown;
      };
  /**
   * Do not install dependency packages.
   */
  skipInstall?: boolean;
  [k: string]: unknown;
}
