name: Builds

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
env:
  NODE_VERSION: 14.x

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: ${{ github.owner }}

      - name: Install
        run: yarn

      - name: Build
        run: yarn run build

    #  - name: Run
    #    run: yarn run dryrun test-env --no-interactive
